DELETE http://localhost:3003/api/blogs/69ba63c384be1797e8d0f738
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1aXBwaTciLCJpZCI6IjY5YjdlYzJkOTE3MmNkMzJkYWI1ODljNCIsImlhdCI6MTc3MzgzMzYwMX0.TqfMe4vrZrReb4RU_nx2S9c0WVezZH_jsMw_JoIwEs4
