POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "juippi7",
    "name": "Julle Julberi",
    "password": "salainen"
}
//    "username": "juippi7",
//    "name": "Julle Julberi",
//    "password": "salainen"
//    token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1aXBwaTciLCJpZCI6IjY5YzRkZDY5NTFhZjMyZGVkYmZlOGU1ZiIsImlhdCI6MTc3NDUwOTQ5NH0.LEjEbu73DgJXJ4Lh6owqKKt37QrL6hvKArZBh68ii3w"

//    "username": "mluukkai",
//    "name": "Matti Luukkainen",
//    "password": "salainen"
//    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IiBtbHV1a2thaSIsImlkIjoiNjljM2NmNTU2YjgwOTJmNjZjNDJiODkwIiwiaWF0IjoxNzc0NDQwNDg5fQ.YGqELXUYOCKJKYmhOc3p9DQeLNgrmlJ_47bVjr4w9Fs"

//------------------------------------------------------------------------------
//haluan 201 created
//
//{
//    "username": "testaaja testaa tokenia",
//    "name": "nimittäjä",
//    "password": "erittainsalainen"
//}

//{
//    "_id":    69bbd200c12c30b148ea4612
//    "username": "uusi user",
//    "name": "uuseri",
//    "password": "salainen"
//    TOKEN eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV1c2kgdXNlciIsImlkIjoiNjliYmQyMDBjMTJjMzBiMTQ4ZWE0NjEyIiwiaWF0IjoxNzczOTE2ODMzfQ.9TOFtZLJfuJ3y29hvg6IrXT4Grlj3RixWirfVEdVDaY
//}

//{
//      id 69bbd56c0d29d9497dc332e1
//    "username": " tosi uusi user",
//    "name": "uuseri",
//    "password": "salainen"
//      TOKEN eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IiB0b3NpIHV1c2kgdXNlciIsImlkIjoiNjliYmQ1NmMwZDI5ZDk0OTdkYzMzMmUxIiwiaWF0IjoxNzczOTE3NTkzfQ.ezrWQGU8IehP3tLMdw1ipOhq6uRlhVwf3f2g1rycQRs
//}