POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "blogi käyttäjällä testi jossa myös käyttäjä saa blogin idn, 2",
    "author": "julle999",
    "url": "osoite",
    "likes": 4
}