POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "testaaja testaa tokenia",
    "name": "nimittäjä",
    "password": "salainen"
}

//haluan 201 created
//
//{
//    "username": "testaaja testaa tokenia",
//    "name": "nimittäjä",
//    "password": "erittainsalainen"
//}

